language: python
cache: pip
sudo: false

# FIXME - ideally need to test on python 2
python:
  - "3.6"
  - "3.7-dev"

install:
  - pip install 'requests>=2.7'
  - pip install tqdm
  - pip install coveralls
  - pip install vcrpy

script:
  - nosetests -v --cover-package=habanero

after_success:
  - coveralls --verbose
