language: python

sudo: false

python:
  - "2.7"

install:
  - pip install 'requests>=2.7'
  - pip install coveralls

script:
  - nosetests -v --with-coverage --cover-package=habanero

after_success:
  - coveralls --verbose
