name: Python

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [3.8.15, 3.9.16, 3.10.9, 3.11.1, 3.11.4]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install habanero
      run: python -m pip install .
    - name: Tests
      run: pytest
    - name: Test coverage
      if: matrix.python-version == '3.11.4'
      run: |
        python -m "pytest" --cov-report=xml --cov=habanero test/
        codecov
